# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'petShop' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MBProgressHUD'
  pod 'Fabric'
  pod 'Crashlytics'
  # Pods for petShop

end
